### ISSUE TITLE
Unable to select items

### ISSUE THREAD

**Issue by Dragsbaek** [minutebase/mb-menu#1]
On selecting an item the action 'on-select' gets called, but the item never gets added to the selected array. Im on ember 1.13.1

**Comment by rlivsey** [comment]
The component doesn't handle manipulating the selected items array, we follow the [data down, actions up](http://www.samselikoff.com/blog/data-down-actions-up/) principle so it's up to whatever component the menu is embedded in to handle what should happen when the action gets called.

The simplest implementation is to add the item to the array when something's selected, but the logic could be much more complicated - the selected items could be a computed property based on other criteria for example - so the menu doesn't need to know anything about this.

**Comment by Dragsbaek** [comment]
Thanks!
